config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get 'home', to: "pages#home" , as: "home"
  get 'about', to: "pages#about" , as: "about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GitDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>


<ul>
<li><%= link_to 'Home', home_path %></li>
</ul>

<p>
We strive to help you learn git.It's our passion.
</p>


app/views/pages/home.html.erb
<h1>Welcome to the Git-hub Demo Web Application</h1>

<p>Homework 4 part3 Step 4 change 1</p>
<p>HW4 part3 Step 4 change 1</p>
<p>HW4 PART3 STEP 6 CHANGE 2</p>


<ul>
<li><%= link_to 'About', about_path %></li>
</ul>
<p>
We really hope that this is helpful!
</p>